version: '3.4'
services:

  sectordb:
    container_name: sectordb
    image: postgres:13
    restart: always
    environment:
      POSTGRES_PASSWORD: sector
      POSTGRES_USER: sector
      POSTGRES_DB: sectordb
    volumes:
      - ./src/main/resources/dbscripts:/docker-entrypoint-initdb.d
    ports:
      - "54322:5432"