spring.datasource.url=jdbc:postgresql://localhost:54322/sectordb
spring.datasource.username=sector
spring.datasource.password=sector

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQL94Dialect

spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp

app.import.file.path=classpath:index.html
welcome.message=Please enter your name and pick the Sectors you are currently involved in: