spring.datasource.url=jdbc:postgresql://localhost:54322/sectordb
spring.datasource.username=sector
spring.datasource.password=sector

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQL94Dialect

spring.thymeleaf.prefix=/WEB-INF/views/
spring.thymeleaf.suffix=.html

app.import.file.path=/WEB-INF/views/index.html