server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sector_db
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  config:
    name: sector-task
